# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2013.4
# Copyright (C) 2013 Xilinx Inc. All rights reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XZbroji" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_HLS_ZBROJI_PERIPH_BUS_BASEADDR" \
        "C_S_AXI_HLS_ZBROJI_PERIPH_BUS_HIGHADDR"

    xdefine_config_file $drv_handle "xzbroji_g.c" "XZbroji" \
        "DEVICE_ID" \
        "C_S_AXI_HLS_ZBROJI_PERIPH_BUS_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XZbroji" \
        "DEVICE_ID" \
        "C_S_AXI_HLS_ZBROJI_PERIPH_BUS_BASEADDR" \
        "C_S_AXI_HLS_ZBROJI_PERIPH_BUS_HIGHADDR"
}

