// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xzbroji.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XZbroji_CfgInitialize(XZbroji *InstancePtr, XZbroji_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Hls_zbroji_periph_bus_BaseAddress = ConfigPtr->Hls_zbroji_periph_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XZbroji_Start(XZbroji *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL) & 0x80;
    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XZbroji_IsDone(XZbroji *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XZbroji_IsIdle(XZbroji *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XZbroji_IsReady(XZbroji *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XZbroji_EnableAutoRestart(XZbroji *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL, 0x80);
}

void XZbroji_DisableAutoRestart(XZbroji *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL, 0);
}

u32 XZbroji_GetReturn(XZbroji *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_RETURN);
    return Data;
}
void XZbroji_SetA(XZbroji *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_A_DATA, Data);
}

u32 XZbroji_GetA(XZbroji *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_A_DATA);
    return Data;
}

void XZbroji_SetB(XZbroji *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_B_DATA, Data);
}

u32 XZbroji_GetB(XZbroji *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_B_DATA);
    return Data;
}

void XZbroji_InterruptGlobalEnable(XZbroji *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_GIE, 1);
}

void XZbroji_InterruptGlobalDisable(XZbroji *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_GIE, 0);
}

void XZbroji_InterruptEnable(XZbroji *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_IER);
    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_IER, Register | Mask);
}

void XZbroji_InterruptDisable(XZbroji *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_IER);
    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_IER, Register & (~Mask));
}

void XZbroji_InterruptClear(XZbroji *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XZbroji_WriteReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_ISR, Mask);
}

u32 XZbroji_InterruptGetEnabled(XZbroji *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_IER);
}

u32 XZbroji_InterruptGetStatus(XZbroji *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XZbroji_ReadReg(InstancePtr->Hls_zbroji_periph_bus_BaseAddress, XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_ISR);
}

