// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xzbroji.h"

extern XZbroji_Config XZbroji_ConfigTable[];

XZbroji_Config *XZbroji_LookupConfig(u16 DeviceId) {
	XZbroji_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XZBROJI_NUM_INSTANCES; Index++) {
		if (XZbroji_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XZbroji_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XZbroji_Initialize(XZbroji *InstancePtr, u16 DeviceId) {
	XZbroji_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XZbroji_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XZbroji_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

