// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

// HLS_ZBROJI_PERIPH_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/SC)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        others - reserved
// 0x10 : reserved
// 0x14 : Data signal of a
//        bit 31~0 - a[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of b
//        bit 31~0 - b[31:0] (Read/Write)
// 0x20 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_CTRL   0x00
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_GIE       0x04
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_IER       0x08
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_ISR       0x0c
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_A_DATA    0x14
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_BITS_A_DATA    32
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_B_DATA    0x1c
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_BITS_B_DATA    32
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_ADDR_AP_RETURN 0x20
#define XZBROJI_HLS_ZBROJI_PERIPH_BUS_BITS_AP_RETURN 32

